import type { Metadata } from "next";
import './globals.css';

//import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primereact/resources/themes/soho-dark/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
// import 'primeflex/primeflex.css';

import { PrimeReactProvider } from 'primereact/api';

export const metadata: Metadata = {
  title: "PUNCHLINE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
